# This file contains all available configuration options
# with their default values.
# Config file reference: https://golangci-lint.run/docs/configuration/file/
# Linters list: https://golangci-lint.run/usage/linters

version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - errname
    - gocritic
    - revive
  disable:
    - errcheck
  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - gocritic
          - revive
  settings:
    revive:
      rules:
        - name: blank-imports
          exclude:
            - "~checksum/algo\\.go$"
    staticcheck:
      checks:
        - "all"
        - "-SA1019"  # Disable warning about using the deprecated algorithms
        - "-ST1003"  # Disable warning about format of CAPS in algorithm names
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
