# This file contains all available configuration options
# with their default values.
# Config file reference: https://golangci-lint.run/docs/configuration/file/
# Linters list: https://golangci-lint.run/usage/linters

version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - errname
    - gocritic
    - revive
  disable:
    - errcheck
  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - gocritic
          - revive
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
