package tusgo

import (
	_ "embed"
	"encoding/json"
	"strconv"
	"strings"
	"testing"
)

// The JSON fixture is generated by api2. This file is the Go-specific test adapter: it decodes
// language-neutral contract facts and exposes the small shapes used by this SDK's behavior tests.
//
//go:embed testdata/api2_tus_contract.json
var generatedTusContractJSON []byte

type generatedTusWireVersion struct {
	Default bool   `json:"default"`
	Value   string `json:"value"`
}

type generatedTusHeaderField struct {
	DisplayName string `json:"displayName"`
	Name        string `json:"name"`
	Required    bool   `json:"required"`
}

type generatedTusHeaderVariant struct {
	Fields []generatedTusHeaderField `json:"fields"`
}

type generatedTusRequestContract struct {
	BodyKind       string                      `json:"bodyKind"`
	ContentType    string                      `json:"contentType"`
	HeaderVariants []generatedTusHeaderVariant `json:"headerVariants"`
}

type generatedTusResponseContract struct {
	StatusCode     int                         `json:"statusCode"`
	BodyKind       string                      `json:"bodyKind"`
	HeaderVariants []generatedTusHeaderVariant `json:"headerVariants"`
}

type generatedTusProtocolOperation struct {
	OperationID string                         `json:"operationId"`
	Role        string                         `json:"role"`
	Method      string                         `json:"method"`
	Path        string                         `json:"path"`
	Request     generatedTusRequestContract    `json:"request"`
	Responses   []generatedTusResponseContract `json:"responses"`
}

type generatedTusClientFeature struct {
	Conformance  generatedTusClientFeatureConformance `json:"conformance"`
	Description  string                               `json:"description"`
	FeatureID    string                               `json:"featureId"`
	Flow         []generatedTusClientFeatureFlowStep  `json:"flow"`
	OperationIDs []string                             `json:"operationIds"`
	Primitives   []string                             `json:"primitives"`
}

type generatedTusClientFeatureConformance struct {
	ScenarioIDs []string `json:"scenarioIds"`
	Status      string   `json:"status"`
}

type generatedTusClientFeatureFlowStep struct {
	Kind        string `json:"kind"`
	OperationID string `json:"operationId"`
	Primitive   string `json:"primitive"`
	Condition   string `json:"condition"`
	Summary     string `json:"summary"`
}

type generatedTusClientUrlStorageConformanceScenario struct {
	Actions    []generatedTusClientUrlStorageConformanceAction `json:"actions"`
	Backend    string                                          `json:"backend"`
	FeatureID  string                                          `json:"featureId"`
	Runtimes   []string                                        `json:"runtimes"`
	ScenarioID string                                          `json:"scenarioId"`
}

type generatedTusClientUrlStorageConformanceAction struct {
	ExpectedKeyPrefix string         `json:"expectedKeyPrefix"`
	ExpectedKeyRefs   []string       `json:"expectedKeyRefs"`
	Fingerprint       string         `json:"fingerprint"`
	KeyRef            string         `json:"keyRef"`
	Kind              string         `json:"kind"`
	Upload            map[string]any `json:"upload"`
}

type generatedTusManagedUploadProofCase struct {
	FeatureID          string
	Layer              string
	ScenarioID         string
	RequiredPrimitives []string
	ProtocolFeatureIDs []string
	RuntimeProfiles    []string
}

type generatedTusContractFixture struct {
	ClientFeatures                       []generatedTusClientFeature                       `json:"clientFeatures"`
	ClientProtocol                       generatedTusClientProtocol                        `json:"clientProtocol"`
	ClientUrlStorageConformanceScenarios []generatedTusClientUrlStorageConformanceScenario `json:"clientUrlStorageConformanceScenarios"`
	ManagedUpload                        generatedTusManagedUpload                         `json:"managedUpload"`
	Operations                           []generatedTusProtocolOperation                   `json:"operations"`
	Versions                             []generatedTusProtocolVersion                     `json:"versions"`
	WireVersions                         []generatedTusWireVersion                         `json:"wireVersions"`
}

type generatedTusClientProtocol struct {
	CompatibilityVersions []generatedTusCompatibilityVersion `json:"compatibilityVersions"`
}

type generatedTusCompatibilityVersion struct {
	ProtocolVersion string                            `json:"protocolVersion"`
	RequestHeaders  []generatedTusContractHeaderValue `json:"requestHeaders"`
	ResponseHeaders []generatedTusContractHeaderValue `json:"responseHeaders"`
}

type generatedTusContractHeaderValue struct {
	HeaderName string `json:"headerName"`
	Value      string `json:"value"`
}

type generatedTusManagedUpload struct {
	FeatureID       string                              `json:"featureId"`
	Flow            []generatedTusManagedUploadFlowStep `json:"flow"`
	Layer           string                              `json:"layer"`
	RuntimeProfiles []generatedTusRuntimeProfile        `json:"runtimeProfiles"`
	Scenarios       []generatedTusManagedUploadScenario `json:"scenarios"`
}

type generatedTusManagedUploadFlowStep struct {
	FeatureID string `json:"featureId"`
	Kind      string `json:"kind"`
}

type generatedTusManagedUploadScenario struct {
	RequiredPrimitives []string `json:"requiredPrimitives"`
	ScenarioID         string   `json:"scenarioId"`
}

type generatedTusProtocolVersion struct {
	Default bool   `json:"default"`
	Value   string `json:"value"`
}

type generatedTusRuntimeProfile struct {
	Runtime string `json:"runtime"`
}

var generatedTusContract = parseGeneratedTusContract()
var generatedTusClientFeatures = generatedTusContract.ClientFeatures
var generatedTusClientUrlStorageConformanceScenarios = generatedTusContract.ClientUrlStorageConformanceScenarios
var generatedTusManagedUploadProofCases = buildGeneratedTusManagedUploadProofCases(generatedTusContract.ManagedUpload)
var generatedTusProtocolOperations = generatedTusContract.Operations
var generatedTusWireVersions = generatedTusContract.WireVersions
var generatedTusDefaultRequestHeaderValues, generatedTusDefaultResponseHeaderValues = generatedTusDefaultHeaderValues(generatedTusContract)

func parseGeneratedTusContract() generatedTusContractFixture {
	var contract generatedTusContractFixture
	if err := json.Unmarshal(generatedTusContractJSON, &contract); err != nil {
		panic("decode generated TUS contract fixture: " + err.Error())
	}
	return contract
}

func generatedTusDefaultHeaderValues(contract generatedTusContractFixture) (map[string]string, map[string]string) {
	defaultProtocolVersion := ""
	for _, version := range contract.Versions {
		if version.Default {
			defaultProtocolVersion = version.Value
			break
		}
	}
	if defaultProtocolVersion == "" {
		panic("generated TUS contract fixture has no default protocol version")
	}

	for _, compatibility := range contract.ClientProtocol.CompatibilityVersions {
		if compatibility.ProtocolVersion != defaultProtocolVersion {
			continue
		}
		return generatedTusHeaderValueMap(compatibility.RequestHeaders), generatedTusHeaderValueMap(compatibility.ResponseHeaders)
	}
	panic("generated TUS contract fixture has no compatibility facts for its default protocol")
}

func generatedTusHeaderValueMap(headers []generatedTusContractHeaderValue) map[string]string {
	values := make(map[string]string, len(headers))
	for _, header := range headers {
		values[header.HeaderName] = header.Value
	}
	return values
}

func buildGeneratedTusManagedUploadProofCases(managedUpload generatedTusManagedUpload) []generatedTusManagedUploadProofCase {
	protocolFeatureIDs := make([]string, 0)
	for _, step := range managedUpload.Flow {
		if step.Kind == "protocol-feature" {
			protocolFeatureIDs = append(protocolFeatureIDs, step.FeatureID)
		}
	}
	runtimeProfiles := make([]string, 0, len(managedUpload.RuntimeProfiles))
	for _, profile := range managedUpload.RuntimeProfiles {
		runtimeProfiles = append(runtimeProfiles, profile.Runtime)
	}

	proofCases := make([]generatedTusManagedUploadProofCase, 0, len(managedUpload.Scenarios))
	for _, scenario := range managedUpload.Scenarios {
		proofCases = append(proofCases, generatedTusManagedUploadProofCase{
			FeatureID:          managedUpload.FeatureID,
			Layer:              managedUpload.Layer,
			ScenarioID:         scenario.ScenarioID,
			RequiredPrimitives: scenario.RequiredPrimitives,
			ProtocolFeatureIDs: protocolFeatureIDs,
			RuntimeProfiles:    runtimeProfiles,
		})
	}
	return proofCases
}

func generatedTusHeaderValue(defaultValues map[string]string, values map[string]string, name string) string {
	if value, ok := values[name]; ok {
		return value
	}
	return defaultValues[name]
}

func generatedTusRequestHeaderValue(values map[string]string, name string) string {
	return generatedTusHeaderValue(generatedTusDefaultRequestHeaderValues, values, name)
}

func generatedTusResponseHeaderValue(values map[string]string, name string) string {
	return generatedTusHeaderValue(generatedTusDefaultResponseHeaderValues, values, name)
}

type generatedTusTestingT interface {
	Fatalf(format string, args ...any)
	Helper()
}

func generatedTusAssertEvents(
	t generatedTusTestingT,
	scenarioID string,
	matching string,
	allowedExtraPrefixes []string,
	expected []string,
	actual []string,
) {
	t.Helper()

	if matching == "exact" {
		if generatedTusStringSlicesEqual(expected, actual) {
			return
		}
		t.Fatalf("expected %s events %#v, got %#v", scenarioID, expected, actual)
	}

	if matching != "exact-except-allowed-extra-events" {
		t.Fatalf("unsupported generated event policy %s for %s", matching, scenarioID)
	}

	expectedIndex := 0
	for _, event := range actual {
		if expectedIndex < len(expected) && event == expected[expectedIndex] {
			expectedIndex++
			continue
		}
		if generatedTusHasAllowedExtraEventPrefix(event, allowedExtraPrefixes) {
			continue
		}
		t.Fatalf(
			"%s emitted unexpected extra event %s; allowed prefixes %#v; expected %#v, got %#v",
			scenarioID,
			event,
			allowedExtraPrefixes,
			expected,
			actual,
		)
	}
	if expectedIndex == len(expected) {
		return
	}
	t.Fatalf(
		"%s did not emit every expected non-extra event; expected %#v, got %#v",
		scenarioID,
		expected,
		actual,
	)
}

func TestGeneratedTusManagedUploadProofCases(t *testing.T) {
	if len(generatedTusManagedUploadProofCases) == 0 {
		t.Fatal("expected generated managed upload proof cases")
	}

	for _, testCase := range generatedTusManagedUploadProofCases {
		if testCase.FeatureID != "managedUpload" {
			t.Fatalf("expected managed upload feature ID, got %s", testCase.FeatureID)
		}
		if testCase.Layer != "feature-over-protocol" {
			t.Fatalf("expected managed upload feature-over-protocol layer, got %s", testCase.Layer)
		}
		if len(testCase.RequiredPrimitives) == 0 {
			t.Fatalf("expected %s required primitives", testCase.ScenarioID)
		}
		if len(testCase.RuntimeProfiles) == 0 {
			t.Fatalf("expected %s runtime profiles", testCase.ScenarioID)
		}
		for _, featureID := range testCase.ProtocolFeatureIDs {
			if generatedTusFindClientFeature(featureID) == nil {
				t.Fatalf(
					"managed upload proof case %s references missing feature %s",
					testCase.ScenarioID,
					featureID,
				)
			}
		}
	}
}

func generatedTusFindClientFeature(featureID string) *generatedTusClientFeature {
	for index := range generatedTusClientFeatures {
		if generatedTusClientFeatures[index].FeatureID == featureID {
			return &generatedTusClientFeatures[index]
		}
	}
	return nil
}

func generatedTusHasAllowedExtraEventPrefix(event string, allowedExtraPrefixes []string) bool {
	for _, prefix := range allowedExtraPrefixes {
		if len(event) >= len(prefix) && event[:len(prefix)] == prefix {
			return true
		}
	}
	return false
}

const generatedTusEventKeyPartSeparator = ":"

func generatedTusEventKey(parts ...string) string {
	return strings.Join(parts, generatedTusEventKeyPartSeparator)
}

func generatedTusEventKeyBool(value bool) string {
	if value {
		return "true"
	}
	return "false"
}

func generatedTusEventKeyNumber(value int64) string {
	return strconv.FormatInt(value, 10)
}

func generatedTusEventKeyAfterResponse(requestIndex string) string {
	return generatedTusEventKey("after-response", requestIndex)
}

func generatedTusEventKeyBeforeRequest(requestIndex string) string {
	return generatedTusEventKey("before-request", requestIndex)
}

func generatedTusEventKeyChunkComplete(chunkSize string, bytesAccepted string, bytesTotal string) string {
	return generatedTusEventKey("chunk-complete", chunkSize, bytesAccepted, bytesTotal)
}

func generatedTusEventKeyFingerprint(fingerprint string) string {
	return generatedTusEventKey("fingerprint", fingerprint)
}

func generatedTusEventKeyProgress(bytesSent string, bytesTotal string) string {
	return generatedTusEventKey("progress", bytesSent, bytesTotal)
}

func generatedTusEventKeyRequestAbort(requestIndex string) string {
	return generatedTusEventKey("request-abort", requestIndex)
}

func generatedTusEventKeyRetrySchedule(delay string) string {
	return generatedTusEventKey("retry-schedule", delay)
}

func generatedTusEventKeyShouldRetry(retryAttempt string, decision string) string {
	return generatedTusEventKey("should-retry", retryAttempt, decision)
}

func generatedTusEventKeySourceClose() string {
	return generatedTusEventKey("source-close")
}

func generatedTusEventKeySourceOpen(inputKind string, size string) string {
	return generatedTusEventKey("source-open", inputKind, size)
}

func generatedTusEventKeySuccess() string {
	return generatedTusEventKey("success")
}

func generatedTusEventKeyUploadUrlAvailable() string {
	return generatedTusEventKey("upload-url-available")
}

func generatedTusEventKeyUrlStorageAdd(fingerprint string, uploadURL string) string {
	return generatedTusEventKey("url-storage-add", fingerprint, uploadURL)
}

func generatedTusEventKeyUrlStorageFind(fingerprint string, count string) string {
	return generatedTusEventKey("url-storage-find", fingerprint, count)
}

func generatedTusEventKeyUrlStorageRemove(urlStorageKey string) string {
	return generatedTusEventKey("url-storage-remove", urlStorageKey)
}

func generatedTusStringSlicesEqual(expected []string, actual []string) bool {
	if len(expected) != len(actual) {
		return false
	}
	for index, expectedValue := range expected {
		if actual[index] != expectedValue {
			return false
		}
	}
	return true
}
